---
- name: Installations
  hosts: production
  become: True
  tasks:
   - name: Installation of Java
     shell: |
       sudo apt update -y
       sudo apt install openjdk-11-jre -y



   - name: Install Jenkins repository key and add repository
     shell: |
       sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
       echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
       sudo apt-get update -y
       sudo apt-get install jenkins -y



   - name: Installation of Docker
     shell: |
       sudo apt-get install ca-certificates curl
       sudo install -m 0755 -d /etc/apt/keyrings
       sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
       sudo chmod a+r /etc/apt/keyrings/docker.asc



   - name: Add repository to Apt sources
     shell: |
       echo \
       "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
       $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
       sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
       sudo apt-get update -y
       sudo apt-get install docker-ce docker-ce-cli containerd.io -y



   - name: Change permission
     file:
       path: /var/run/docker.sock
       mode: "777"